vich_uploader:
    db_driver: orm
    mappings:
        report_data:
            uri_prefix: '%app.path.report_data%'
            upload_destination: '%kernel.project_dir%/public%app.path.report_data%'
#            namer:
#                service: Vich\UploaderBundle\Naming\PropertyNamer
#                options: { property: 'report' }