version: '3.8'

x-cache-from:
  - &app-cache-from
    cache_from:
      - php:8.0-fpm

services:
  nginx:
    container_name: hackathon_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php
    ports:
      - "8080:80"
      - "443:443"

  php:
    container_name: hackathon_php
    image: php:8.0-fpm
    build:
      context: ./docker/php-fpm
      <<: *app-cache-from
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - ./:/var/www
      - app-cache:/var/www/var

  db:
    container_name: hackathon_postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  adminer:
    container_name: hackathon_adminer
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  wp:
    container_name: hackhaton_wp
    image: wordpress
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: wp_db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp_pwd
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html

  wp_db:
    container_name: hackhaton_wp_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp_pwd
      MYSQL_ROOT_PASSWORD: wp_root_pwd
    volumes:
      - wp-db-data:/var/lib/mysql

#  mailer:
#    image: schickling/mailcatcher
#    ports: [ 1025, 1080 ]

volumes:
  db-data: {}
  app-cache: {}
  wp-db-data: {}
